# prom-agent-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-agent-config
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      external_labels:
        cluster: datacenter

    scrape_configs:
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: ['prometheus']
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: node-exporter
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: metrics
          - target_label: job
            replacement: node-exporter

    remote_write:        # ✅ scrape_configs와 같은 레벨
      - url: http://192.168.1.231:9090/api/v1/write
        queue_config:
          max_shards: 4
          capacity: 10000
          max_samples_per_send: 1000

