apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-inputgen-deployment
  namespace: service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
        - name: inputgen00
          image: kyla333/inputgen0
