apiVersion: apps/v1
kind: Deployment
metadata:
  name: kmsg-inputgen-deployment
  namespace: system
spec:
  replicas: 2
  selector:
    matchLabels:
      system: kmsg
  template:
    metadata:
      labels:
        system: kmsg
    spec:
      containers:
        - name: kmsg-inputgen
          image: kyla333/inputgen5
