apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom-inputgen-deployment
  namespace: system
spec:
  replicas: 2
  selector:
    matchLabels:
      system: oom
  template:
    metadata:
      labels:
        system: oom
    spec:
      containers:
        - name: oom-inputgen
          image: kyla333/inputgen1
