apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: efkstack
data:
  fluent.conf: |
    ############################################################
    # 1) Fluent Bit → Fluentd 입력 (forward)
    ############################################################
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    ############################################################
    # 2) 서비스 애플리케이션 로그 → Kafka 전송 (service-topic)
    ############################################################
    <match service.application.log>
      @type kafka2
      brokers 192.168.1.210:9094
      topic service-topic
      use_event_time true

      <format>
        @type json
      </format>

      <buffer>
        @type memory
        flush_interval 5s
        flush_at_shutdown true
        flush_thread_count 2
        chunk_limit_size 1m
        retry_max_interval 30
        retry_forever true
      </buffer>
    </match>

    ############################################################
    # 3-1) 시스템 로그 → OOM (system-oom-topic)
    ############################################################
    <match system.oom.log>
      @type kafka2
      brokers 192.168.1.210:9094
      topic system-oom-topic
      use_event_time true

      <format>
        @type json
      </format>

      <buffer>
        @type memory
        flush_interval 5s
        flush_at_shutdown true
        flush_thread_count 2
        chunk_limit_size 1m
        retry_max_interval 30
        retry_forever true
      </buffer>
    </match>

    ############################################################
    # 3-2) 시스템 로그 → MCE (system-mce-topic)
    ############################################################
    <match system.mce.log>
      @type kafka2
      brokers 192.168.1.210:9094
      topic system-mce-topic
      use_event_time true

      <format>
        @type json
      </format>

      <buffer>
        @type memory
        flush_interval 5s
        flush_at_shutdown true
        flush_thread_count 2
        chunk_limit_size 1m
        retry_max_interval 30
        retry_forever true
      </buffer>
    </match>

    ############################################################
    # 3-3) 시스템 로그 → DISK (system-disk-topic)
    ############################################################
    <match system.disk.log>
      @type kafka2
      brokers 192.168.1.210:9094
      topic system-disk-topic
      use_event_time true

      <format>
        @type json
      </format>

      <buffer>
        @type memory
        flush_interval 5s
        flush_at_shutdown true
        flush_thread_count 2
        chunk_limit_size 1m
        retry_max_interval 30
        retry_forever true
      </buffer>
    </match>

    ############################################################
    # 3-4) 시스템 로그 → AUTH (system-auth-topic)
    ############################################################
    <match system.auth.log>
      @type kafka2
      brokers 192.168.1.210:9094
      topic system-auth-topic
      use_event_time true

      <format>
        @type json
      </format>

      <buffer>
        @type memory
        flush_interval 5s
        flush_at_shutdown true
        flush_thread_count 2
        chunk_limit_size 1m
        retry_max_interval 30
        retry_forever true
      </buffer>
    </match>

    ############################################################
    # 4) 매칭 안 된 나머지 (디버깅용)
    ############################################################
    <match **>
      @type stdout
    </match>

